package:
  name: condapackage
  version: 7.7

source:
  git_url: https://github.com/MichelML/condapackage.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - setuptools
