package:
  name: condapackage
  version: 7.7

source:
  url: https://github.com/MichelML/condapackage.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - click

about:
  home: https://github.com/pallets/click
